[package]
name = "bella-core"
version.workspace = true
edition.workspace = true

[[bin]]
name = "bellad"
path = "src/main.rs"

[dependencies]
bella-common = { path = "../bella-common" }
bella-permissions = { path = "../bella-permissions" }
bella-memory = { path = "../bella-memory" }
async-trait.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
